"""fix json type and update campaign daily_cap

Revision ID: 6f7a8f1e1745
Revises: 0001_initial
Create Date: 2026-09-26 14:15:23.461358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f7a8f1e1745'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad_units', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('ad_units', sa.Column('format_type', sa.Enum('DISPLAY', 'BANNER', 'NATIVE', 'VIDEO', 'INTERSTITIAL', name='adformattype', native_enum=False), nullable=False))
    op.add_column('ad_units', sa.Column('reserve_price', sa.Numeric(precision=10, scale=4), nullable=False))
    op.add_column('ad_units', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('ad_units', sa.Column('allow_house_ads', sa.Boolean(), nullable=False))
    op.add_column('ad_units', sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True))
    op.alter_column('ad_units', 'id',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('ad_units', 'publisher_id',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_ad_units_format_type'), 'ad_units', ['format_type'], unique=False)
    op.create_index(op.f('ix_ad_units_is_active'), 'ad_units', ['is_active'], unique=False)
    op.create_index('ix_ad_units_matching_lookup', 'ad_units', ['is_active', 'width', 'height', 'format_type'], unique=False)
    op.create_index(op.f('ix_ad_units_publisher_id'), 'ad_units', ['publisher_id'], unique=False)
    op.create_unique_constraint('uq_publisher_slot_name', 'ad_units', ['publisher_id', 'slot_name'])
    op.create_foreign_key(None, 'ad_units', 'publishers', ['publisher_id'], ['id'], ondelete='CASCADE')
    op.add_column('advertisers', sa.Column('company_legal_name', sa.String(length=255), nullable=True))
    op.add_column('advertisers', sa.Column('website_url', sa.String(length=2048), nullable=True))
    op.add_column('advertisers', sa.Column('industry', sa.String(length=100), nullable=True))
    op.add_column('advertisers', sa.Column('status', sa.Enum('PENDING_VERIFICATION', 'ACTIVE', 'SUSPENDED', 'ARCHIVED', name='accountstatus', native_enum=False), nullable=False))
    op.add_column('advertisers', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('advertisers', sa.Column('phone_number', sa.String(length=32), nullable=True))
    op.add_column('advertisers', sa.Column('vat_number', sa.String(length=64), nullable=True))
    op.add_column('advertisers', sa.Column('currency', sa.Enum('USD', 'EUR', 'GBP', name='currency', native_enum=False), nullable=False))
    op.add_column('advertisers', sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('advertisers', sa.Column('credit_limit', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('advertisers', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('advertisers', 'id',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_advertisers_billing_email'), 'advertisers', ['billing_email'], unique=False)
    op.create_index(op.f('ix_advertisers_industry'), 'advertisers', ['industry'], unique=False)
    op.create_index(op.f('ix_advertisers_name'), 'advertisers', ['name'], unique=False)
    op.create_index(op.f('ix_advertisers_status'), 'advertisers', ['status'], unique=False)
    op.create_index('ix_advertisers_status_created', 'advertisers', ['status', 'created_at'], unique=False)
    op.add_column('campaigns', sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'ACTIVE', 'PAUSED', 'COMPLETED', 'EXHAUSTED', 'ARCHIVED', name='campaignstatus', native_enum=False), nullable=False))
    op.add_column('campaigns', sa.Column('bidding_strategy', sa.Enum('CPM', 'CPC', 'CPA', name='biddingstrategy', native_enum=False), nullable=False))
    op.add_column('campaigns', sa.Column('bid_amount', sa.Numeric(precision=10, scale=4), nullable=False))
    op.add_column('campaigns', sa.Column('total_budget', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('campaigns', sa.Column('spent_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.alter_column('campaigns', 'id',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('campaigns', 'advertiser_id',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('campaigns', 'end_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('campaigns', 'daily_cap',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.create_index('ix_campaigns_ad_server_lookup', 'campaigns', ['is_active', 'status', 'start_date', 'end_date', 'priority'], unique=False)
    op.create_index(op.f('ix_campaigns_advertiser_id'), 'campaigns', ['advertiser_id'], unique=False)
    op.create_index(op.f('ix_campaigns_end_date'), 'campaigns', ['end_date'], unique=False)
    op.create_index(op.f('ix_campaigns_name'), 'campaigns', ['name'], unique=False)
    op.create_index(op.f('ix_campaigns_start_date'), 'campaigns', ['start_date'], unique=False)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_foreign_key(None, 'campaigns', 'advertisers', ['advertiser_id'], ['id'], ondelete='CASCADE')
    op.add_column('creatives', sa.Column('name', sa.String(length=200), nullable=True))
    op.add_column('creatives', sa.Column('impression_tracker_url', sa.String(length=2048), nullable=True))
    op.add_column('creatives', sa.Column('html_snippet', sa.Text(), nullable=True))
    op.add_column('creatives', sa.Column('custom_attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True))
    op.add_column('creatives', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('creatives', sa.Column('review_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='reviewstatus', native_enum=False), nullable=False))
    op.add_column('creatives', sa.Column('rejection_reason', sa.String(length=500), nullable=True))
    op.add_column('creatives', sa.Column('weight', sa.Integer(), nullable=False))
    op.alter_column('creatives', 'id',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('creatives', 'campaign_id',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('creatives', 'asset_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000),
               type_=sa.String(length=2048),
               existing_nullable=False)
    op.alter_column('creatives', 'click_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000),
               type_=sa.String(length=2048),
               existing_nullable=False)
    op.alter_column('creatives', 'format',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.Enum('IMAGE', 'HTML', 'VIDEO', 'NATIVE', name='creativeformat', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'image'"))
    op.create_index('ix_creatives_ad_matching', 'creatives', ['campaign_id', 'is_active', 'review_status', 'width', 'height'], unique=False)
    op.create_index(op.f('ix_creatives_campaign_id'), 'creatives', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_creatives_format'), 'creatives', ['format'], unique=False)
    op.create_index(op.f('ix_creatives_review_status'), 'creatives', ['review_status'], unique=False)
    op.create_foreign_key(None, 'creatives', 'campaigns', ['campaign_id'], ['id'], ondelete='CASCADE')
    op.add_column('events', sa.Column('event_id', sa.UUID(as_uuid=False), nullable=True))
    op.add_column('events', sa.Column('cost', sa.Numeric(precision=10, scale=6), nullable=False))
    op.add_column('events', sa.Column('is_valid', sa.Boolean(), nullable=False))
    op.add_column('events', sa.Column('user_ip', postgresql.INET(), nullable=True))
    op.add_column('events', sa.Column('user_agent', sa.String(length=512), nullable=True))
    op.add_column('events', sa.Column('country_code', sa.String(length=2), nullable=True))
    op.alter_column('events', 'id',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('events', 'ad_unit_id',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('events', 'campaign_id',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('events', 'creative_id',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('events', 'type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.Enum('IMPRESSION', 'CLICK', 'CONVERSION', 'VIEWABLE_IMPRESSION', name='eventtype', native_enum=False),
               existing_nullable=False)
    op.drop_index(op.f('ix_events_campaign_id_timestamp'), table_name='events')
    op.create_index(op.f('ix_events_ad_unit_id'), 'events', ['ad_unit_id'], unique=False)
    op.create_index('ix_events_ad_unit_time', 'events', ['ad_unit_id', 'type', 'timestamp'], unique=False)
    op.create_index(op.f('ix_events_campaign_id'), 'events', ['campaign_id'], unique=False)
    op.create_index('ix_events_campaign_time', 'events', ['campaign_id', 'type', 'timestamp'], unique=False)
    op.create_index(op.f('ix_events_country_code'), 'events', ['country_code'], unique=False)
    op.create_index(op.f('ix_events_creative_id'), 'events', ['creative_id'], unique=False)
    op.create_index(op.f('ix_events_event_id'), 'events', ['event_id'], unique=True)
    op.create_index(op.f('ix_events_is_valid'), 'events', ['is_valid'], unique=False)
    op.create_index(op.f('ix_events_timestamp'), 'events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_events_type'), 'events', ['type'], unique=False)
    op.create_index('ix_events_type_valid_time', 'events', ['type', 'is_valid', 'timestamp'], unique=False)
    op.create_foreign_key(None, 'events', 'campaigns', ['campaign_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'events', 'ad_units', ['ad_unit_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'events', 'creatives', ['creative_id'], ['id'], ondelete='CASCADE')
    op.add_column('publishers', sa.Column('domain', sa.String(length=255), nullable=True))
    op.add_column('publishers', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('publishers', sa.Column('status', sa.Enum('PENDING_APPROVAL', 'ACTIVE', 'SUSPENDED', 'REJECTED', name='publisherstatus', native_enum=False), nullable=False))
    op.add_column('publishers', sa.Column('ads_txt_verified', sa.Boolean(), nullable=False))
    op.add_column('publishers', sa.Column('revenue_share_percentage', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('publishers', sa.Column('unpaid_earnings', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('publishers', sa.Column('payout_email', sa.String(length=255), nullable=False))
    op.add_column('publishers', sa.Column('payment_method', sa.Enum('STRIPE', 'PAYPAL', 'WIRE_TRANSFER', name='paymentmethod', native_enum=False), nullable=True))
    op.add_column('publishers', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('publishers', 'id',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('api_key'), table_name='publishers')
    op.drop_index(op.f('ix_publishers_api_key'), table_name='publishers')
    op.create_index(op.f('ix_publishers_api_key'), 'publishers', ['api_key'], unique=True)
    op.create_index(op.f('ix_publishers_domain'), 'publishers', ['domain'], unique=False)
    op.create_index(op.f('ix_publishers_name'), 'publishers', ['name'], unique=False)
    op.create_index(op.f('ix_publishers_payout_email'), 'publishers', ['payout_email'], unique=False)
    op.create_index(op.f('ix_publishers_status'), 'publishers', ['status'], unique=False)
    op.create_index('ix_publishers_status_active', 'publishers', ['status', 'is_active'], unique=False)
    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('mfa_enabled', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('mfa_secret', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_login_ip', sa.String(length=45), nullable=True))
    op.alter_column('users', 'id',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.Enum('ADMIN', 'PUBLISHER', 'ADVERTISER', name='userrole', native_enum=False),
               existing_nullable=False)
    op.alter_column('users', 'publisher_id',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('users', 'advertiser_id',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.drop_index(op.f('email'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_advertiser_id'), 'users', ['advertiser_id'], unique=False)
    op.create_index(op.f('ix_users_publisher_id'), 'users', ['publisher_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index('ix_users_role_active', 'users', ['role', 'is_active'], unique=False)
    op.create_foreign_key(None, 'users', 'publishers', ['publisher_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'users', 'advertisers', ['advertiser_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'users', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index('ix_users_role_active', table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_publisher_id'), table_name='users')
    op.drop_index(op.f('ix_users_advertiser_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'advertiser_id',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.alter_column('users', 'publisher_id',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'PUBLISHER', 'ADVERTISER', name='userrole', native_enum=False),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('users', 'last_login_ip')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'mfa_secret')
    op.drop_column('users', 'mfa_enabled')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_index('ix_publishers_status_active', table_name='publishers')
    op.drop_index(op.f('ix_publishers_status'), table_name='publishers')
    op.drop_index(op.f('ix_publishers_payout_email'), table_name='publishers')
    op.drop_index(op.f('ix_publishers_name'), table_name='publishers')
    op.drop_index(op.f('ix_publishers_domain'), table_name='publishers')
    op.drop_index(op.f('ix_publishers_api_key'), table_name='publishers')
    op.create_index(op.f('ix_publishers_api_key'), 'publishers', ['api_key'], unique=False)
    op.create_index(op.f('api_key'), 'publishers', ['api_key'], unique=True)
    op.alter_column('publishers', 'id',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('publishers', 'notes')
    op.drop_column('publishers', 'payment_method')
    op.drop_column('publishers', 'payout_email')
    op.drop_column('publishers', 'unpaid_earnings')
    op.drop_column('publishers', 'revenue_share_percentage')
    op.drop_column('publishers', 'ads_txt_verified')
    op.drop_column('publishers', 'status')
    op.drop_column('publishers', 'category')
    op.drop_column('publishers', 'domain')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'events', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'events', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_index('ix_events_type_valid_time', table_name='events')
    op.drop_index(op.f('ix_events_type'), table_name='events')
    op.drop_index(op.f('ix_events_timestamp'), table_name='events')
    op.drop_index(op.f('ix_events_is_valid'), table_name='events')
    op.drop_index(op.f('ix_events_event_id'), table_name='events')
    op.drop_index(op.f('ix_events_creative_id'), table_name='events')
    op.drop_index(op.f('ix_events_country_code'), table_name='events')
    op.drop_index('ix_events_campaign_time', table_name='events')
    op.drop_index(op.f('ix_events_campaign_id'), table_name='events')
    op.drop_index('ix_events_ad_unit_time', table_name='events')
    op.drop_index(op.f('ix_events_ad_unit_id'), table_name='events')
    op.create_index(op.f('ix_events_campaign_id_timestamp'), 'events', ['campaign_id', 'timestamp'], unique=False)
    op.alter_column('events', 'type',
               existing_type=sa.Enum('IMPRESSION', 'CLICK', 'CONVERSION', 'VIEWABLE_IMPRESSION', name='eventtype', native_enum=False),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=False)
    op.alter_column('events', 'creative_id',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('events', 'campaign_id',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('events', 'ad_unit_id',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('events', 'id',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('events', 'country_code')
    op.drop_column('events', 'user_agent')
    op.drop_column('events', 'user_ip')
    op.drop_column('events', 'is_valid')
    op.drop_column('events', 'cost')
    op.drop_column('events', 'event_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'creatives', type_='foreignkey')
    op.drop_index(op.f('ix_creatives_review_status'), table_name='creatives')
    op.drop_index(op.f('ix_creatives_format'), table_name='creatives')
    op.drop_index(op.f('ix_creatives_campaign_id'), table_name='creatives')
    op.drop_index('ix_creatives_ad_matching', table_name='creatives')
    op.alter_column('creatives', 'format',
               existing_type=sa.Enum('IMAGE', 'HTML', 'VIDEO', 'NATIVE', name='creativeformat', native_enum=False),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'image'"))
    op.alter_column('creatives', 'click_url',
               existing_type=sa.String(length=2048),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000),
               existing_nullable=False)
    op.alter_column('creatives', 'asset_url',
               existing_type=sa.String(length=2048),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000),
               existing_nullable=False)
    op.alter_column('creatives', 'campaign_id',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('creatives', 'id',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('creatives', 'weight')
    op.drop_column('creatives', 'rejection_reason')
    op.drop_column('creatives', 'review_status')
    op.drop_column('creatives', 'is_active')
    op.drop_column('creatives', 'custom_attributes')
    op.drop_column('creatives', 'html_snippet')
    op.drop_column('creatives', 'impression_tracker_url')
    op.drop_column('creatives', 'name')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_start_date'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_name'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_end_date'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_advertiser_id'), table_name='campaigns')
    op.drop_index('ix_campaigns_ad_server_lookup', table_name='campaigns')
    op.alter_column('campaigns', 'daily_cap',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('campaigns', 'end_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('campaigns', 'advertiser_id',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('campaigns', 'id',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('campaigns', 'spent_amount')
    op.drop_column('campaigns', 'total_budget')
    op.drop_column('campaigns', 'bid_amount')
    op.drop_column('campaigns', 'bidding_strategy')
    op.drop_column('campaigns', 'status')
    op.drop_index('ix_advertisers_status_created', table_name='advertisers')
    op.drop_index(op.f('ix_advertisers_status'), table_name='advertisers')
    op.drop_index(op.f('ix_advertisers_name'), table_name='advertisers')
    op.drop_index(op.f('ix_advertisers_industry'), table_name='advertisers')
    op.drop_index(op.f('ix_advertisers_billing_email'), table_name='advertisers')
    op.alter_column('advertisers', 'id',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('advertisers', 'notes')
    op.drop_column('advertisers', 'credit_limit')
    op.drop_column('advertisers', 'balance')
    op.drop_column('advertisers', 'currency')
    op.drop_column('advertisers', 'vat_number')
    op.drop_column('advertisers', 'phone_number')
    op.drop_column('advertisers', 'is_verified')
    op.drop_column('advertisers', 'status')
    op.drop_column('advertisers', 'industry')
    op.drop_column('advertisers', 'website_url')
    op.drop_column('advertisers', 'company_legal_name')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'ad_units', type_='foreignkey')
    op.drop_constraint('uq_publisher_slot_name', 'ad_units', type_='unique')
    op.drop_index(op.f('ix_ad_units_publisher_id'), table_name='ad_units')
    op.drop_index('ix_ad_units_matching_lookup', table_name='ad_units')
    op.drop_index(op.f('ix_ad_units_is_active'), table_name='ad_units')
    op.drop_index(op.f('ix_ad_units_format_type'), table_name='ad_units')
    op.alter_column('ad_units', 'publisher_id',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('ad_units', 'id',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('ad_units', 'settings')
    op.drop_column('ad_units', 'allow_house_ads')
    op.drop_column('ad_units', 'is_active')
    op.drop_column('ad_units', 'reserve_price')
    op.drop_column('ad_units', 'format_type')
    op.drop_column('ad_units', 'description')
    # ### end Alembic commands ###